export const productTypes = [
  { code: 0, name: 'All Products' },
  { code: '20002', name: 'POST-NEGOTIATION ODA' },
  { code: '10008', name: 'APG PROCEEDS ACCOUNT - INDIVIDUAL' },
  { code: 'ASSTS', name: 'ASSET2 ACCOUNT' },
  { code: 'EXPNE', name: 'EXPENSES2 ACCOUNTS' },
  { code: 'LIABT', name: 'LIABILITIES2 ACCOUNTS' },
  { code: 'INCME', name: 'INCOME2 ACCOUNT' },
  { code: '60002', name: 'ROYAL KIDDIES ACCOUNT' },
  { code: '60003', name: 'PURPLE ACCOUNT' },
  { code: '63002', name: 'WEMA TARGET SAVINGS ACCOUNT' },
  { code: 'DUMMY', name: 'DUMMY MIGRATION' },
  { code: '19999', name: 'BAD BANK -ODA BAD BANK' },
  { code: '60005', name: 'VISA FIXED - INDIVIDUAL' },
  { code: '60006', name: 'VISA FIXED - NON INDIVIDUAL' },
  { code: '10009', name: 'CREDIT CARD - INDIVIDUAL' },
  { code: '10010', name: 'CREDIT CARD - NON INDIVIDUAL' },
  { code: 'AI019', name: 'AGRIC INPUT - GES ACCOUNT' },
  { code: '10007', name: 'APG PROCEEDS ACCOUNT - CORPORATE' },
  { code: '60007', name: 'MOMENT ACCOUNT-OSUN FARMERS' },
  { code: '20003', name: 'INTEREST PAID DISCOUNTING LINE' },
  { code: '10011', name: 'MY BUSINESS ACCOUNT' },
  { code: '10012', name: 'MY BUSINESS ACCOUNT -SILVER' },
  { code: '10013', name: 'MY BUSINESS ACCOUNT -GOLD' },
  { code: 'MC001', name: 'EXPRESS CREDIT' },
  { code: '60008', name: 'EASY LIFE' },
  { code: 'AL001', name: 'SCHOOL FEES ADVANCE' },
  { code: '20001', name: 'PRE-NEGOTIATION ODA' },
  { code: '72001', name: 'SMART SAVE ACCT' },
  { code: 'IS002', name: 'CURRENT ACCOUNT' },
  { code: '70006', name: 'TIME -OTHER FINANCIAL INSTITUTION' },
  { code: '71006', name: 'CALL -OTHER FINANCIAL INSTITUTION' },
  { code: '60009', name: 'EASYLIFE UPLIFT' },
  { code: '10043', name: 'PCA PLUS' },
  { code: '60010', name: 'ALAT ACCOUNT' },
  { code: '60011', name: 'ALAT GOAL' },
  { code: '60004', name: 'MOMENT ACCOUNT' },
  { code: 'TRANS', name: 'TRANSIT ACCOUNTS' },
  { code: '60012', name: 'ALAT LITE' },
  { code: '62003', name: 'WEMA TREASURE ACCOUNT - BUSINESS' },
  { code: '30003', name: 'DOMICILLIARY PLUS INDIVIDUAL' },
  { code: '30004', name: 'DOMICILIARY PLUS NON-INDIVIDUAL' },
  { code: 'SF006', name: 'DBN MSMEDF SCHEME NON-EI' },
  { code: 'SF007', name: 'DBN MSMEDF SCHEME EI' },
  { code: 'CA003', name: 'COMMERCIAL AGRIC CREDIT SCHEME_NON_EI' },
  { code: '60001', name: 'SAVINGS ACCOUNT INDIVIDUAL' },
  { code: '30001', name: 'DOMICILIARY ACCOUNT - EXPORT' },
  { code: '70001', name: 'TERM DEPOSIT - INDIVIDUALS' },
  { code: '71010', name: 'FDPLUS' },
  { code: 'SF004', name: 'MSMEDF SCHEME-EI' },
  { code: 'RE005', name: 'REAL ESTATE FINANCE' },
  { code: 'EL007', name: 'EQUIPMENT LEASE' },
  { code: 'CF008', name: 'CONTRACT FINANCE FACILITY' },
  { code: 'MF001', name: 'MORTGAGE FINANCE' },
  { code: 'LP009', name: 'LOCAL PURCHASE ORDER' },
  { code: 'EF011', name: 'EXPORT FINANCE' },
  { code: 'CP012', name: 'COMMERCIAL PAPER ASSET' },
  { code: 'RF013', name: 'RECEIVABLE REFINANCE FACILITY' },
  { code: 'DP015', name: 'DUTY PAYMENT' },
  { code: 'LC016', name: 'LC CONFIRMATION/ FINANCE LINE' },
  { code: 'IF010', name: 'IMPORT FINANCE' },
  { code: '10001', name: 'CURRENT ACCOUNT - INDIVIDUAL' },
  { code: '60111', name: 'SAVINGS ACCOUNT NON INDIVIDUAL' },
  { code: 'ASSET', name: 'ASSET ACCOUNT' },
  { code: '30002', name: 'DOMICILIARY ACCOUNT - NON EXPORT' },
  { code: '71001', name: 'CALL DEPOSIT INDIVIDUAL' },
  { code: '71002', name: 'CALL DEPOSIT NON-INDIVIDUAL' },
  { code: '71003', name: 'CALL DEPOSIT STAFF' },
  { code: '71004', name: 'CALL DEPOSIT PUBLIC SECTOR' },
  { code: '71005', name: 'CALL DEPOSIT CORPORATE' },
  { code: 'PC101', name: 'PRE-SHIPMENT CREDIT SCHEME' },
  { code: 'FB102', name: 'DOMESTIC INWARD BILLS PURCHASED & DISCOUNTED' },
  { code: 'DDA01', name: 'MANAGERS CHEQUE LOCAL' },
  { code: 'PROXY', name: 'PROXY' },
  { code: 'CASH', name: 'CASH ACCOUNT' },
  { code: 'OAPCP', name: 'OFFICE A/C POINTING CR' },
  { code: 'OAPDP', name: 'OFFICE A/C POINTING DR' },
  { code: 'FB101', name: 'POST SHIPMENT FINANCING' },
  { code: 'WETSA', name: 'WEMA TARGET SAVINGS ACCOUNT' },
  { code: '10014', name: 'CURRENT - LOCAL GOVERNMENT' },
  { code: '70002', name: 'TERM DEPOSIT - NON INDIVIDUALS' },
  { code: '70003', name: 'TERM DEPOSIT - STAFF' },
  { code: '70004', name: 'TERM DEPOSIT - CORPORATE' },
  { code: '70005', name: 'TERM DEPOSIT - PUBLIC SECTOR' },
  { code: 'AG001', name: 'AGRICULTURAL FINANCE_NON-EI' },
  { code: 'AG002', name: 'AGRIC CREDIT GUARANTEE SCHEME FUND_NON_EI' },
  { code: 'AG003', name: 'AGRIC CREDIT SUPPORT SCHEME_NON_EI' },
  { code: 'WA005', name: 'WEMA ASSET ACQUISITION SCHEME' },
  { code: 'BO006', name: 'BOI - REFINANCE SCHEME' },
  { code: 'PF001', name: 'PROJECT FINANCE FACILITY' },
  { code: 'OF002', name: 'OBJECT FINANCE' },
  { code: 'EXPNS', name: 'EXPENSES ACCOUNTS' },
  { code: 'LIABL', name: 'LIABILITIES ACCOUNTS' },
  { code: 'TRADE', name: 'TRADING ACCOUNT' },
  { code: 'CONAS', name: 'CONTINGENT ASSETS ACCOUNT' },
  { code: 'CONLI', name: 'CONTINGENT LIABILITY ACC' },
  { code: 'INCOM', name: 'INCOME ACCOUNT' },
  { code: 'SYSAC', name: 'SYSTEM ACCOUNTS' },
  { code: '62001', name: 'WEMA TREASURE ACCOUNT - INDIVIDUAL' },
  { code: '62002', name: 'WEMA TREASURE ACCOUNT - NON INDIVIDUAL' },
  { code: '60021', name: 'SAVINGS ACCOUNT STAFF' },
  { code: '60051', name: 'SAVINGS ACCOUNT SALARY' },
  { code: '10004', name: 'CURRENT ACCOUNT - PUBLIC SECTOR' },
  { code: '10041', name: 'PRESTIGE CURRENT ACCOUNT - INDIVIDUAL' },
  { code: '10006', name: 'CURRENT ACCOUNT -BDC' },
  { code: 'MF002', name: 'MORTGAGE FINANCE_EI' },
  { code: 'AG004', name: 'AGRICULTURAL FINANCE' },
  { code: 'AG005', name: 'AGRIC CREDIT GUARANTEE SCHEME FUND' },
  { code: 'AG006', name: 'AGRIC CREDIT SUPPORT SCHEME' },
  { code: 'PF002', name: 'PROJECT FINANCE FACILITY' },
  { code: 'WA006', name: 'WEMA ASSET ACQUISITION SCHEME_NON-EI' },
  { code: 'BO007', name: 'BOI - REFINANCE SCHEME_NON-EI' },
  { code: 'OF003', name: 'OBJECT FINANCE' },
  { code: '10042', name: 'MY BUSINESS ACCOUNT PLUS' },
  { code: 'MT017', name: 'MARGIN TRADING FACILITY' },
  { code: '10005', name: 'CURRENT ACCOUNT NON-RESIDENT' },
  { code: '10002', name: 'CURRENT ACCOUNT - NON INDIVIDUAL' },
  { code: '10003', name: 'CURRENT ACCOUNT - CORPORATE' },
  { code: '10021', name: 'STAFF CURRENT ACCOUNT' },
  { code: 'WH018', name: 'WAREHOUSING FINANCE FACILITY' },
  { code: '10071', name: 'BOI OVERDRAFT' },
  { code: '10121', name: 'SALARY CURRENT ACCOUNT' },
  { code: 'LC017', name: 'LC CONFIRMATION/ FINANCE LINE' },
  { code: 'CA004', name: 'COMMERCIAL AGRIC CREDIT SCHEME' },
  { code: 'SF005', name: 'MSMEDF SCHEME-NON-EI' },
  { code: 'RE006', name: 'REAL ESTATE FINANCE' },
  { code: 'EL008', name: 'EQUIPMENT LEASE' },
  { code: 'CF009', name: 'CONTRACT FINANCE FACILITY' },
  { code: 'LP010', name: 'LOCAL PURCHASE ORDER' },
  { code: 'IF011', name: 'IMPORT FINANCE' },
  { code: 'EF012', name: 'EXPORT FINANCE' },
  { code: 'RF014', name: 'RECEIVABLE REFINANCE FACILITY' },
  { code: 'DP016', name: 'DUTY PAYMENT' },
  { code: '60013', name: 'ALAT MEDIUM' },
  { code: 'AG007', name: 'AGSMEIS SCHEME EMI' },
  { code: '60014', name: 'PURPLE PLUS ACCOUNT' },
  { code: 'AG008', name: 'AGSMEIS SCHEME NON-EI' },
  { code: '60112', name: 'SAVINGS -LOCAL GOVERNMENT' }
];
